DATA:
  ROOT: "D:/Learn/machine_learning/data/iwslt2017-en-de/en-de"
MODEL:
  LAYER_NUM: 6
  D_MODEL: 512
  HEAD: 8
  EPS: 1.0e-05
  D_FF: null
  DROPOUT: 0.1
  MAX_LENGTH: 1024
LR:
  BETA1: 0.9
  BETA2: 0.98
  L_EPS: 1.0e-09
  WARMUP: 4000
TRAIN:
  EPOCHS: 1
  BATCH_SIZE: 8  # 停用
  MAX_BATCH_LENGTH: 12000
  MAX_TOKENS: 12000
VAL:
  RUN_BLEU: true
TEST:
  MAX_GENERATE_LENGTH: 512
  MODE: val  # val: 验证, dev2010; test: 测试, tst2010-2012 逐句语料级 BLEU + tst2010/2011/2012 三个分年子分数
  BLEU_TOKENIZE: intl
BPE:
  IS_TRAINED: true
  VOCAB_SIZE: 32000
  CHARACTER_COVERAGE: 0.9995
  MODEL_TYPE: bpe
  NUM_THREADS: 4
  PAD_ID: 0
  UNK_ID: 1
  BOS_ID: 2
  EOS_ID: 3
  MERGE_SIZE: 5
