# ============================================================
# 超参数配置
# ============================================================
MODEL:
  LAYER_NUM : 6
  D_MODEL : 512
  HEAD : 8
  EPS : !!float 1e-5
  D_FF : null
  DROPOUT : 0.1
  MAX_LENGTH : 128
LR:
  BETA1 : 0.9
  BETA2 : 0.98
  L_EPS : !!float 1e-9
  WARMUP : 4000
TRAIN:
  EPOCHS : 5
  BATCH_SIZE : 8
BPE:
  IS_TRAINED : !!bool True            # BPE 模型是否已经训练完毕
  VOCAB_SIZE : 32000                  # BPE 词汇量（IWSLT 常用 32k）
  CHARACTER_COVERAGE : 0.9995         # 覆盖德语的特殊字符（ä ü ö ß）
  MODEL_TYPE : "bpe"                  # BPE 算法
  NUM_THREADS : 4
  PAD_ID : 0                          # <pad> 索引 0
  UNK_ID : 1                          # <unk> 索引 1
  BOS_ID : 2                          # <s>  索引 2
  EOS_ID : 3                          # </s> 索引 3
  MERGE_SIZE : 5